### ISSUE TITLE
Support for Wordpress Plugin Boilerplate style plugins

### ISSUE THREAD

**Issue by nextgenthemes** [sun/wordpress-git-svn-release#6]
https://github.com/tommcfarlin/WordPress-Plugin-Boilerplate

There should be a grep be `* Version` as well, currently it does only work if the Version is at the line beginning.

Also plugins with this style have a `class.plugins-name.php` file with a `const VERSION =` that should also be checked.

**Comment by sun** [comment]
Hm.  Not sure I'm able to follow.  Can you create a PR?

AFAICS, `Version` should be parsed correctly, there doesn't seem to be a difference to the recommended WP.org docs.

For the second issue, I assume we need to add a new, optional `$MAINCLASSFILE` property to `.wp-release.conf` that specifies a class file?

If specified, we'd `grep -E 'const VERSION *= *'` ?

**Comment by nextgenthemes** [comment]
I use another script now, this is no longer important to me.

I simply wanted this script to detect the version correctly `LINEBEGIN Version` works `LINEBEGIN * Version` works not.
